name: hitch Tests

on:
  workflow_call:

jobs:
  build_wolfssl:
    name: Build wolfSSL
    # Just to keep it the same as the testing target
    runs-on: ubuntu-latest
    steps:
      - name: Build wolfSSL
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          path: wolfssl
          configure: --enable-hitch
          install: true

      - name: Upload built lib
        uses: actions/upload-artifact@v3
        with:
          name: wolf-install-hitch
          path: build-dir
          retention-days: 1

  hitch_check:
    strategy:
      fail-fast: false
      matrix:
        # List of releases to test
        ref: [ 1.7.3 ]
    name: ${{ matrix.ref }}
    runs-on: ubuntu-latest
    needs: build_wolfssl
    steps:
      - name: Download lib
        uses: actions/download-artifact@v3
        with:
          name: wolf-install-hitch
          path: build-dir

      - name: Checkout OSP
        uses: actions/checkout@v3
        with:
          # TODO: change to wolfssl repo once merged
          repository: kareem-wolfssl/osp
          ref: hitch
          path: osp

      - name: Install dependencies
        run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update
            sudo apt-get install -y libev-dev libssl-dev automake python3-docutils flex bison pkg-config make

      - name: Checkout hitch
        uses: actions/checkout@v3
        with:
          # TODO: change to wolfssl repo once merged
          repository: varnish/hitch
          ref: 1.7.3
          path: hitch

      - name: Debug hitch configure
        run: |
            cd $GITHUB_WORKSPACE/hitch/
            patch -p1 < $GITHUB_WORKSPACE/osp/hitch/hitch_1.7.3.patch
            autoreconf -ivf
            SSL_CFLAGS="-I$GITHUB_WORKSPACE/build-dir/include/ -I$GITHUB_WORKSPACE/build-dir/include/wolfssl" SSL_LIBS="-L$GITHUB_WORKSPACE/build-dir/lib -lwolfssl" ./configure --with-wolfssl=$GITHUB_WORKSPACE/build-dir/ --enable-silent-rules --enable-documentation --enable-warnings --with-lex --with-yacc --prefix=$GITHUB_WORKSPACE/build-dir
            make -j$(nproc)

      #- name: Build hitch
        #uses: wolfSSL/actions-build-autotools-project@v1
        #with:
          #repository: varnish/hitch
          #ref: ${{ matrix.ref }}
          #path: hitch
          #patch-file: $GITHUB_WORKSPACE/osp/hitch/hitch_${{ matrix.ref }}.patch
          #configure: >-
            #  --with-wolfssl=$GITHUB_WORKSPACE/build-dir/ --enable-silent-rules --enable-documentation --enable-warnings --with-lex --with-yacc
            #  SSL_CFLAGS="-I$GITHUB_WORKSPACE/build-dir/include/ -I$GITHUB_WORKSPACE/build-dir/include/wolfssl" SSL_LIBS="-L$GITHUB_WORKSPACE/build-dir/lib -lwolfssl"

      - name: Confirm hitch built with wolfSSL
        working-directory: ./hitch
        run: ldd src/hitch | grep wolfssl

      - name: Run hitch tests, skipping 13, 15 and 39
        run: |
          cd src/tests
          for test in ./test*.sh; do
            if ! [[ "$test" = ./test13* ]] && ! [[ "$test" = ./test15* ]] && ! [[ "$test" = ./test39* ]]; then
              $test
            fi
          done